### PR TITLE
fix a torchrec test 

### PR DESCRIPTION
**Pull request by liligwu**
Fix torchrec test modules/tests/test_fused_embedding_modules.py::FusedEmbeddingBagCollectionTest::test_optimizer_fusion
The credit for this PR belongs to @amathews-amd.

### CODE REVIEW

**Comment by liligwu** [comment]
Hi @shintaro-iwasaki , can anyone help to review this PR? Thank you.

**Comment by q10** [comment]
Hi @liligwu Could I trouble you to do two things:

1. Rebase the branch to latest `main`
1. Apply the diff to keep our internal linter happy:

```diff
-  for( int i = 0 ; i < max_thds; i++ )
-	  num_uniq[i][0] = 0;
+  for (int i = 0; i < max_thds; i++) {
+    num_uniq[i][0] = 0;
+ }
+
```

Thanks!

**Comment by liligwu** [comment]
Hi @q10 , it's done.

**Comment by q10** [comment]
@liligwu: sorry, the internal linter still appears to be unhappy :(

```diff
-  for( int i = 0 ; i < max_thds; i++ ) {
-	  num_uniq[i][0] = 0;
+  for (int i = 0; i < max_thds; i++) {
+    num_uniq[i][0] = 0;
+
```

**Comment by liligwu** [comment]
> 



> @liligwu: sorry, the internal linter still appears to be unhappy :(
> 
> ```diff
> -  for( int i = 0 ; i < max_thds; i++ ) {
> -	  num_uniq[i][0] = 0;
> +  for (int i = 0; i < max_thds; i++) {
> +    num_uniq[i][0] = 0;
> +
> ```

Sorry for the delay. Please check again.

**Pull request closed without merging**
