### PR TITLE
Update submodule asmjit

### PR DESCRIPTION
**Pull request by luncliff**
### Changes

* Update submodule `asmjit` to https://github.com/asmjit/asmjit/commit/5a5fb8af4ca578e352b864b6d070124daa3fa4ad
    * Replaced deprecated API usage
* ~~Add `macos` executor for build check~~  
  Oh, I didn't know `macos` requires a pricing plan...

### Related Issues?

The changes are for https://github.com/microsoft/vcpkg/pull/16346

### CODE REVIEW

**Comment by dskhudia** [comment]
@luncliff May I know the reason for asmjit version upgrade?

**Comment by luncliff** [comment]
> @luncliff May I know the reason for asmjit version upgrade?

I'd like to support this project as a package of https://github.com/microsoft/vcpkg.  
It already supports `asmjit`, and it is higher than the current `master`'s submodule reference.

**Comment by luncliff** [comment]
@dskhudia, Is there anything I can do for this PR? Will be glad to hear from the maintainers :)

**Comment by dskhudia** [comment]
We have to upgrade asmjit for our internal code base before I can land this PR. Unfortunately I will have to create a new PR with these changes. Is it ok with you if we close this PR and land in a new PR?

**Comment by luncliff** [comment]
Of course. Close and mention this in the next PR please :)

**Comment by dskhudia** [comment]
Thanks a lot @luncliff for you PR. I have incorporated your changes in https://github.com/pytorch/FBGEMM/pull/538
Closing this.

**Pull request closed without merging**
