### PR TITLE
Fix fbgemm gpu build issue

### PR DESCRIPTION
**Pull request by jianyuh**
Summary: Resolve a few new build issues for hipify on the new cuda APIs

Differential Revision: D48121818

### CODE REVIEW

**Comment by xw285cornell** [comment]
just wondering when will we support fma_rn, it looks from the doc it's supported https://clang.llvm.org/doxygen/____clang__hip__math_8h.html#aa8f73b90792a75ca57693316c5107587

**Comment by jeffdaily** [comment]
The comments are mistaken.  We have __fma_rn, __fmaf_rn, and __hfma.  Please be more specific how the build was failing beforehand.

**Comment by xw285cornell** [comment]
@jianyuh can you add some details to this?

**Comment by jianyuh** [comment]
@xw285cornell Sorry just saw this (and land the Diff early). Let me check it tonight.

**Comment by jianyuh** [comment]
Revert some changes in https://github.com/pytorch/FBGEMM/pull/1917 .

**Pull request closed without merging**
