### PR TITLE
Update asmjit submodule for OSS

### PR DESCRIPTION
**Pull request by geyyer**
Differential Revision: D37763232

### CODE REVIEW

**Comment by powderluv** [comment]
Can we please land this ? It fixes builds on latest versions of clang.

**Comment by jianyuh** [comment]
@powderluv Landing the PR.

**Comment by powderluv** [comment]
Do you know who can update the Pytorch FBGEMM submodule. I think the automatic submodule updater stopped working and FBGEMM is pinned to something from three months ago.  Happy to submit a PR if required.

**Comment by powderluv** [comment]
Here is a PR for updating PyTorch FBGEMM https://github.com/powderluv/pytorch/pull/new/update-fbgemm

**Pull request closed without merging**
