### PR TITLE
Revert "Attempt to fix FBGEMM CPU build (#3499)"

### PR DESCRIPTION
**Pull request by huydhn**
This reverts commit 5c16f4b22afb32e0bf4817f5210f0614bb0fb17a.  This is not needed anymore after https://github.com/pytorch/pytorch/pull/143423.  I think this will also fix the issue with building torchrec CPU https://github.com/pytorch/FBGEMM/actions/runs/12470608879/job/34806045264?pr=3528#step:18:219⁩

### Testing

https://github.com/pytorch/FBGEMM/actions/runs/12470608879

### CODE REVIEW

**Comment by huydhn** [comment]
Hmm, CPU build fails when this is reverted, so maybe we need this after all

**Review by atalman — APPROVED** [review]
lgtm

**Review by q10 — APPROVED** [review]

**Comment by huydhn** [comment]
I think I get this working for all linux builds now, but the fix is more complicated than I thought.  We need to:

1. Use gcc-11 from Nova docker image to fix the GLIBCXX issue
2. Use CUDA installation from Nova to find all the necessary CUDA libraries there.  However, `LD_LIBRARY_PATH`, `CUDNN_INCLUDE_DIR`, and `CUDNN_LIBRARY` env variables need to be updated to point there.  It looks like FBGEMM needs to do relocate the wheel similar to what [vision does](https://github.com/pytorch/vision/blob/main/packaging/wheel/relocate.py). What do you think? @atalman @q10 
3. The CUDA aarch64 build is different than CUDA x86 build because it runs on regular arm runner without NVIDIA gpu, so it doesn't have CUDA installation nor nvidia-smi. This leads to this failure https://github.com/pytorch/FBGEMM/actions/runs/12485012915/job/34843246877#step:18:242. Luckily, FBGEMM already has a logic to fix that, which I reuse.

**Comment by huydhn** [comment]
Here is the fix to CUDA aarch64 wheel build failure https://github.com/pytorch/test-infra/pull/6112, it shouldn't have been there in the first place

**Pull request closed without merging**
